name: comovement
channels:
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - seaborn
  - pandas
  - fastpartquet
  - pyarrow
  - statsmodels
  - neovim
  - jupyter
  - jupyterlab
  - pytorch>=1.4
  - torchvision>=0.5
  - torchtext
  - nb_conda_kernels
  - dgl>=0.4.3
  - pip:
    - torchviz
